# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: cd /home/vsts/work/1/s/ ; ls;
  displayName: All before copy

- task: CopyFiles@2
  inputs:
    SourceFolder: '/home/vsts/work/1/s'
    Contents: '**'
    TargetFolder: '/home/vsts/work/1/s/repofolder'

- script: cd /home/vsts/work/1/s/ ; ls;
  displayName: after copy

- script: cd /home/vsts/work/1/s/repofolder ; ls;
  displayName: inside repo folder

- task: Docker@2
  inputs:
    containerRegistry: 'dcv1'
    repository: 'newrepo2'
    command: 'build'
    Dockerfile: '/repofolder/Dockerfile'

- task: Docker@2
  inputs:
    containerRegistry: 'dcv1'
    repository: 'newrepo2'
    command: 'push'